# Generated by Django 4.2.30 on 2026-08-24 16:44

import LR.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addressLine1', models.CharField(blank=True, max_length=250, null=True)),
                ('addressLine2', models.CharField(blank=True, max_length=250, null=True)),
                ('area', models.CharField(blank=True, max_length=250, null=True)),
                ('city', models.CharField(max_length=250)),
                ('state', models.CharField(blank=True, choices=[('BR', 'Bihar')], max_length=250, null=True)),
                ('country', models.CharField(blank=True, choices=[('IN', 'India')], max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=250, null=True)),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('contactNumber', models.BigIntegerField(blank=True, null=True)),
                ('contactPerson', models.CharField(blank=True, max_length=250, null=True)),
                ('tin', models.CharField(blank=True, max_length=250, null=True)),
                ('isActive', models.BooleanField(default=True)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('addressLine1', models.CharField(blank=True, max_length=250, null=True)),
                ('addressLine2', models.CharField(blank=True, max_length=250, null=True)),
                ('area', models.CharField(blank=True, max_length=250, null=True)),
                ('city', models.CharField(blank=True, max_length=250, null=True)),
                ('state', models.CharField(blank=True, choices=[('BR', 'Bihar')], max_length=250, null=True)),
                ('country', models.CharField(blank=True, choices=[('IN', 'India')], max_length=250, null=True)),
            ],
            options={
                'verbose_name': 'Customers',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_detail', models.TextField(blank=True, default='[]', null=True, validators=[LR.utils.validate_json])),
                ('expenses_detail', models.TextField(blank=True, default='[]', null=True, validators=[LR.utils.validate_json])),
                ('misc_cash_in_details', models.TextField(blank=True, default='[]', null=True, validators=[LR.utils.validate_json])),
                ('day_card_sale', models.FloatField(blank=True, default=0, null=True)),
                ('bank_deposit', models.FloatField(blank=True, default=0, null=True)),
                ('day_credit_sale', models.FloatField(blank=True, default=0, null=True)),
                ('total_expense', models.FloatField(blank=True, default=0, null=True)),
                ('total_credit_purchase', models.FloatField(blank=True, default=0, null=True)),
                ('total_cash_purchase', models.FloatField(blank=True, default=0, null=True)),
                ('opening_balance', models.FloatField(blank=True, default=0, null=True)),
                ('total_misc_cash_in', models.FloatField(blank=True, default=0, null=True)),
                ('cash_inhand', models.FloatField(blank=True, default=0, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('day_cash_sale', models.FloatField(blank=True, default=0, null=True)),
                ('branch_name', models.CharField(blank=True, max_length=50, null=True)),
                ('day_cash_difference', models.FloatField(blank=True, default=0, null=True)),
                ('is_editable', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ResetId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forwardingNoteId', models.BigIntegerField(blank=True, null=True)),
                ('dispatchId', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('address_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='LR.address')),
                ('name', models.CharField(max_length=250)),
                ('code', models.CharField(max_length=250)),
                ('vat', models.CharField(default=True, max_length=250, null=True)),
                ('cst_or_tin', models.CharField(default=True, max_length=250, null=True)),
            ],
            bases=('LR.address',),
        ),
        migrations.CreateModel(
            name='Consignor',
            fields=[
                ('address_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='LR.address')),
                ('name', models.CharField(max_length=250)),
                ('contactNumber', models.BigIntegerField()),
                ('contactPerson', models.CharField(blank=True, max_length=250, null=True)),
                ('isActive', models.BooleanField(default=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name': 'Consignor',
                'ordering': ('name',),
            },
            bases=('LR.address',),
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('address_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='LR.address')),
                ('label', models.CharField(max_length=250)),
            ],
            bases=('LR.address',),
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ForwardingNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billDates', models.CharField(blank=True, max_length=250, null=True)),
                ('transporterStation', models.CharField(blank=True, max_length=250, null=True)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('billNo', models.CharField(blank=True, max_length=250, null=True)),
                ('billValues', models.CharField(blank=True, max_length=250, null=True)),
                ('cases', models.CharField(blank=True, max_length=250, null=True)),
                ('regularCases', models.CharField(blank=True, max_length=250, null=True)),
                ('bigCases', models.CharField(blank=True, max_length=250, null=True)),
                ('marka', models.CharField(blank=True, max_length=250, null=True)),
                ('permitNo', models.CharField(blank=True, max_length=250, null=True)),
                ('commodity', models.CharField(blank=True, max_length=250, null=True)),
                ('isDispatched', models.BooleanField(default=False)),
                ('fnDate', models.DateTimeField()),
                ('slug', models.BigIntegerField(blank=True, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='LR.customer')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='LR.company')),
                ('consignor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='LR.consignor')),
            ],
        ),
        migrations.CreateModel(
            name='Dispatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('vanNo', models.CharField(blank=True, max_length=250, null=True)),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('remarks', models.CharField(blank=True, max_length=250, null=True)),
                ('isLocked', models.BooleanField(default=True)),
                ('slug', models.BigIntegerField(blank=True, null=True)),
                ('forwardingNote', models.ManyToManyField(to='LR.forwardingnote')),
            ],
            options={
                'verbose_name': 'Dispatche',
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LR.organization'),
        ),
        migrations.CreateModel(
            name='Transporter',
            fields=[
                ('address_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='LR.address')),
                ('name', models.CharField(max_length=250)),
                ('contactNumber', models.CharField(blank=True, max_length=250, null=True)),
                ('contactPerson', models.CharField(blank=True, max_length=250, null=True)),
                ('isActive', models.BooleanField(default=True)),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LR.organization')),
                ('stations', models.ManyToManyField(to='LR.station')),
            ],
            options={
                'verbose_name': 'Consignor',
                'ordering': ('name',),
            },
            bases=('LR.address',),
        ),
        migrations.AddField(
            model_name='forwardingnote',
            name='transporter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LR.transporter'),
        ),
        migrations.AddField(
            model_name='consignor',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LR.organization'),
        ),
        migrations.AddField(
            model_name='company',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LR.organization'),
        ),
    ]
