# Generated by Django 4.2.30 on 2026-08-24 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=250, null=True)),
                ('cst', models.CharField(blank=True, max_length=250, null=True)),
                ('tin', models.CharField(blank=True, max_length=250, null=True)),
                ('address_Line1', models.CharField(blank=True, max_length=250, null=True)),
                ('address_Line2', models.CharField(blank=True, max_length=250, null=True)),
                ('city', models.CharField(blank=True, max_length=250, null=True)),
                ('state', models.CharField(blank=True, max_length=250, null=True)),
                ('postal_Code', models.CharField(blank=True, max_length=250, null=True)),
                ('phone', models.CharField(blank=True, max_length=250, null=True)),
                ('email', models.CharField(blank=True, max_length=250, null=True)),
                ('country', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('address', models.ManyToManyField(to='stock.address')),
            ],
        ),
        migrations.CreateModel(
            name='SupplyPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('0', 'In'), ('1', 'Out')], max_length=250)),
                ('bill_No', models.CharField(blank=True, max_length=250, null=True)),
                ('bill_Date', models.DateField(blank=True, null=True)),
                ('bill_Rec_Date', models.DateField(blank=True, null=True)),
                ('bill_Amount', models.FloatField(blank=True, null=True)),
                ('lr_No', models.CharField(blank=True, max_length=250, null=True)),
                ('lr_Date', models.DateField(blank=True, null=True)),
                ('cases', models.CharField(blank=True, max_length=250, null=True)),
                ('carriers_Name', models.CharField(blank=True, max_length=250, null=True)),
                ('permit_No', models.CharField(blank=True, max_length=250, null=True)),
                ('permit_Amt', models.FloatField(blank=True, null=True)),
                ('doc_Month', models.CharField(blank=True, max_length=250, null=True)),
                ('F_C_O', models.CharField(blank=True, max_length=250, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('qrt', models.CharField(blank=True, max_length=250, null=True)),
                ('year', models.CharField(blank=True, max_length=250, null=True)),
                ('remarks', models.CharField(blank=True, max_length=250, null=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.address')),
                ('commodity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.commodity')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.company')),
            ],
        ),
    ]
